# Generated by Django 2.0.7 on 2020-06-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
